### ISSUE TITLE
Date is not corect when clicking in an EditText field under Registering, Export and TimeLogging

### ISSUE THREAD

**Issue by a7med-95** [MarkusAJacobsen/NABL#25]
The month is 0-based => Jan = 0, etc ..

**Comment by MarkusAJacobsen** [comment]
https://developer.android.com/reference/java/util/Calendar.html#MONTH

**Comment by a7med-95** [comment]
True

**Comment by MarkusAJacobsen** [comment]
So they are sat by constants. So to fetch them from an Calendar object use https://developer.android.com/reference/java/util/Calendar.html#get(int)

**Comment by a7med-95** [comment]
Just to make sure ... dud you fix this issue on registering too ?

**Comment by MarkusAJacobsen** [comment]
It isn't as much a "fix" as not understanding how to use the Calendar Library 
![image](https://user-images.githubusercontent.com/18272698/39482821-ca56aadc-4d70-11e8-9649-2385a20e985a.png)

But, no there are no issue with project registration

**Comment by MarkusAJacobsen** [comment]
Fixed
